### ISSUE TITLE
Guide to use (? 

### ISSUE THREAD

**Issue by Askeshine** [psFrankenstein/jsProblem#2]
Any doc for use ? examples ? idk what a need to do them put in jspdf.js

**Comment by psFrankenstein** [comment]
This is a simple function you can call from your jspdf just put that function on your js call it where you want and sent the required parameters.  too simple  .this function break your require string in a small string and decorate  part by part then put all the part together again for output . it  will just save some time that's it .you can simple use  this or you can create your won
